"""Open ArgonDB — Enterprise-equivalent features for ArangoDB Community Edition."""

__version__ = "0.1.0"

from open_argondb.core import ArgonDB
from open_argondb.models import (
    AgentScope,
    AuthResult,
    BackupConfig,
    ChangeEvent,
    Contradiction,
    EdgeDefinition,
    EncryptionRequirement,
    EncryptionStatus,
    GraphConfig,
    LDAPConfig,
    Memory,
    PartitionKey,
    ReplicationConfig,
    RestoreConfig,
    RetrievalConfig,
    RetrievalRequest,
    RetrievalResult,
    RoleMapping,
    SatelliteConfig,
    SnapshotConfig,
    SupersessionChain,
    TemporalQuery,
    TraversalResult,
    Visibility,
)

__all__ = [
    "AgentScope",
    "ArgonDB",
    "AuthResult",
    "BackupConfig",
    "ChangeEvent",
    "Contradiction",
    "EdgeDefinition",
    "EncryptionRequirement",
    "EncryptionStatus",
    "GraphConfig",
    "LDAPConfig",
    "Memory",
    "PartitionKey",
    "ReplicationConfig",
    "RestoreConfig",
    "RetrievalConfig",
    "RetrievalRequest",
    "RetrievalResult",
    "RoleMapping",
    "SatelliteConfig",
    "SnapshotConfig",
    "SupersessionChain",
    "TemporalQuery",
    "TraversalResult",
    "Visibility",
]
